Add functional and tests
DaniilRyndyk1/java-explore-with-me pull request #4
Opened 2023-09-05 11:59 UTC by DaniilRyndyk1

2023-09-06 11:04 UTC, Fleaman777 requested changes

2023-09-06 11:04 UTC, Fleaman777 commented on .github/workflows/api-tests.yml
> -name: Explore With Me API Tests
вообще все эти файлы, которые были изначально, удалять не надо, 
благодаря им как раз проходит вся проверка

2023-09-06 11:04 UTC, Fleaman777 commented on ewm-stat-service/service/src/test/java/ru/practicum/statservice/service/EndpointHitServiceTest.java
> +}
респект за тесты

2023-09-06 11:04 UTC, Fleaman777 commented on ewm-stat-service/service/src/main/java/ru/practicum/statservice/service/EndpointHitService.java
> +    public void create(EndpointHitInputDto dto) {
метод изменяет состояние БД, правильней было бы его выполнять в транзакции,

2023-09-06 15:09 UTC, DaniilRyndyk1 commented on ewm-stat-service/service/src/main/java/ru/practicum/statservice/service/EndpointHitService.java
> +        if (isUrisNull) {
Поправил, изначально хотел многоуровневую проверку сделать

2023-09-06 15:12 UTC, DaniilRyndyk1 commented on .github/workflows/api-tests.yml
> -name: Explore With Me API Tests
Вернул, пропали случайно, когда пришлось откатить часть коммитов

2023-09-07 05:40 UTC, Fleaman777 requested changes
Почти все отлично, 
большую часть файлов вернул, не без усилий, но вернул, молодец! 
осталось еще немного

2023-09-07 05:40 UTC, Fleaman777 commented on pom.xml
> -
эту часть конфигурации в мавен так же, хорошо бы вернуть, 
аналагично с файлами: 
suppressions.xml
lombok.config
ewm-main-service-spec.json
README

2023-09-07 09:09 UTC, DaniilRyndyk1 commented on pom.xml
> -
Вернул потерянные файлы

2023-09-08 05:38 UTC, Fleaman777 approved these changes
отлично, теперь все на месте, можно принимать

2023-09-08 10:03 UTC, merged